[package]
authors = ["Allen Conlon <allen@conlon.dev"]
edition = "2021"
name = "rust-testing"
description = "A simple Rust project using Nix"
version = "0.1.1"
license = "MIT"

[dependencies]
actix-web = "4.9.0"
serde = { version = "1.0.209", features = ["derive"] }
num = "0.4.3"
env_logger = "0.11.5"
log = "0.4.22"
