[package]
authors = ["Allen Conlon <allen@conlon.dev"]
edition = "2021"
name = "rust-testing"
description = "A simple Rust project using Nix"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.93"
# rand = "0.8.5"
# gethostname = "0.5.0"
# hostname = "0.4.0"

[dev-dependencies]
wasm-bindgen-test = "0.3.43"
