[package]
authors = ["Allen Conlon <allen@conlon.dev"]
edition = "2021"
name = "rust-testing"
description = "A simple Rust project using Nix"
version = "0.1.0"
license = "MIT"

[dependencies]
rocket = "0.5.1"
