[package]
authors = [ "Allen Conlon <allen@conlon.dev>" ]
edition = "2021"
name = "package-builder"
description = "Project to build a zarf.yaml file from a bigbang release"
version = "0.0.1"
license = "MIT"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
serde = { version = "1.0.210", features = ["derive"]}
serde_yaml_ng = "0.10"
schema-lib = { path = "schema-lib" }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[workspace]
members = [ "schema-lib" ]

[workspace.package]
edition = "2021"
license = "MIT"
authors = [ "Allen Conlon <allen@conlon.dev>" ]
