[package]
authors = [ "Allen Conlon <allen@conlon.dev" ]
edition = "2021"
name = "zarf-injector"
description = "A simple Rust project using Nix"
version = "0.1.1"
license = "MIT"

[dependencies]
glob = "0.3.1"
flate2 = "1.0.28"
tar = "0.4.40"
sha2 = "0.10.8"
hex = {version = "0.4.3", default-features = false}
serde_json = { version = "1.0.113", default-features = false, features = ["alloc"] }
axum = {version = "0.7.5", features = ["tokio"]}
tokio = { version = "1.35.0", features = ["fs", "rt"] }
tokio-util = { version = "0.7.10", features = ["io"]}
regex-lite = "0.1.5"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
