[package]
authors = [ "Allen Conlon <allen@conlon.dev" ]
edition = "2021"
name = "rust-testing"
description = "A simple Rust project using Nix"
version = "0.1.1"
license = "MIT"

[dependencies]
serde = {version = "1.0.210", features = ["derive"]}
serde_yaml_ng = "0.10"
schemars = "0.8"
typify = "0.1.0"

[workspace]
members = [ "rust-testing-lib" ]

[workspace.package]
edition = "2021"
license = "MIT"
authors = [ "Allen Conlon <allen@conlon.dev" ]
