[package]
authors = [ "Allen Conlon <allen@conlon.dev>" ]
edition = "2021"
name = "appz"
description = "Playground"
version = "0.0.1"
license = "MIT"

[dependencies]
actix-web = "4.9.0"
env_logger = "0.11.5"
log = "0.4.22"
serde = { version = "1.0.210", features = ["derive"] }
# libraries
linkage-lib = { path = "lib/linkage" }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[workspace]
members = [ "lib/linkage", "lib/schema" ]

[workspace.package]
edition = "2021"
license = "MIT"
authors = [ "Allen Conlon <allen@conlon.dev>" ]

[workspace.dependencies]
serde = { version = "1.0.210", features = ["derive"] }
serde_json = { version = "1.0.128" }
