[package]
authors = ["Allen Conlon <allen@conlon.dev"]
edition = "2021"
name = "rust-testing"
description = "A simple Rust project using Nix"
version = "0.1.0"
license = "MIT"

[dependencies]
built = {version = "0.7.4", features = ["chrono", "semver"]}
hostname = "0.4.0"
rocket = {version = "0.5.1", features = ["json", "msgpack", "uuid"]}
num = "0.4.3"

[build-dependencies]
built = { version = "0.7", features = ["cargo-lock", "dependency-tree", "git2", "chrono", "semver"] }
