[package]
name = "rust-testing-lib"
version = "0.0.1"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "A simple Rust project using Nix, library"

[dependencies]
num = "0.4.3"
serde = { version = "1.0.209", features = ["derive"] }
