[package]
authors.workspace = true
edition.workspace = true
name = "rust-testing-lib"
description = "A simple Rust project using Nix, library"
version = "0.0.1"
license.workspace = true

[dependencies]
num = "0.4.3"
serde = { version = "1.0.209", features = ["derive"] }
