[package]
name = "rust-testing-lib"
version = "0.0.1"
authors = ["Allen Conlon <allen@conlon.dev"]
edition = "2021"
license = "MIT"
description = "A simple Rust project using Nix, library"

[dependencies]
num = "0.4.3"
serde = { version = "1.0.209", features = ["derive"] }
