[package]
name = "schema-lib"
version = "0.0.1"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Library that holds the schemas"

[dependencies]
num = "0.4.3"
serde = { version = "1.0.210", features = ["derive"] }
