---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
name: "CI Nix"
on:
  # Run only when pushing to master branch, and making PRs
  push:
    branches:
    - main
  pull_request:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: DeterminateSystems/nix-installer-action@b92f66560d6f97d6576405a7bae901ab57e72b6a # v15
      with:
        extra-conf: |
          trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          substituters = https://cache.garnix.io?priority=41 https://cache.nixos.org/
    - name: Setup CI environment
      id: ci-env
      run: |
        nix build .#version
        echo "version=$(cat result)" >>$GITHUB_OUTPUT
    - name: Login to Github Container Registry
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - env:
        IMAGE: ${{ steps.ci-env.outputs.version }}
      run: |
        nix build .#image
        docker load -i result
        docker push $IMAGE
