on: [push]
name: CI
jobs:
  check:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Install latest nightly
      uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy
    # `cargo check` command here will use installed `nightly`
    # as it is set as an "override" for current directory
    - name: Run cargo check
      uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1.0.3
      with:
        command: check
